apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-dynamic-sc
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: Pod
metadata: 
  name: efs-static-pod
  labels:
    purpose: efs-dynamic-demo
    project: roboshop
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
      - name: persistent-volume
        mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-volume
    persistentVolumeClaim:
      claimName: efs-dynamic-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: efs-dynamic-service
  labels:
    purpose: efs-dynamic-demo
    project: roboshop
spec:
  selector:
    purpose: efs-dynamic-demo
    project: roboshop
  type: LoadBalancer
  ports:
    - protocol : TCP
      port: 80
      targetPort: 80