apiVersion: v1
kind: Pod
metadata:
  name: multi-containers-demo
  labels:
    check: "multi-containers running or not"
  containers:
  - name: nginx
    image: nginx
  
  - name: almalinux
    image: almalinux:9