apiVersion: v1
kind: Pod
metadata:
  name: resources
  labels:
    purpose: resources-check

spec:
  containers:
  - name: nginx
    image: nginx
  resources:
    requests:
      memory: "65Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "150m"