apiVersion: v1
kind: Service
metadata:
  name: latest-nginx
  labels:
    purpose: testing-service-attachments
spec:
  selector:
    project: roboshop
    environment: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80