apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    purpose: service-demo
    project: roboshop
    env: dev
spec:
  selectors:
    purpose: service-demo
    project: roboshop
    env: dev
  ports:
    - protocol: TCP
      port: 80 # host port
      targetPort: 80 # container port


---

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: service-demo
    project: roboshop
    env: dev
spec:
  - name: nginx
    image: nginx

