apiVersion: v1
kind: Service
metadata:
  name: service-np
  labels:
    purpose: service-demo-np
    project: roboshop
    env: dev
spec:
  type: NodePort
  selector:
    purpose: service-demo-np
    project: roboshop
    env: dev
  ports:
    - protocol: TCP
      port: 80 # host port
      targetPort: 80 # container port



---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-np
  labels:
    purpose: service-demo-np
    project: roboshop
    env: dev
spec:
  containers:
    - name: nginx
      image: nginx

---


apiVersion: v1
kind: Pod
metadata:
  name: nginx-np-1
  labels:
    purpose: service-demo-np
    project: roboshop
    env: dev
spec:
  containers:
    - name: nginx
      image: nginx
