apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: demo-rs-la
  labels:
    purpose: demo-replicas
    project: roboshop
    env: dev
spec:
  replicas: 15
  selector:
    matchLabels:
      purpose: demo-replicas
      project: roboshop
      env: dev
  template:
    metadata:
      labels:
        purpose: demo-replicas
        project: roboshop
        env: dev
    spec:
      containers:
        - name: nginx
          image: nginx:stable-perl


# the created 3 replica pods are not accessable externally, until u create a service to expose them
