apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-demo
  labels:
    purpose: deployment-demo
    project: roboshop
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      purpose: deployment-demo
      project: roboshop
      env: dev
  template:
    metadata:
      labels:
         purpose: deployment-demo
         project: roboshop
         env: dev
    spec:
      containers:
        - name: nginx
          image: nginx