# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: ebs-dynamic-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: ebs-dynamic-sc
#   resources:
#     requests:
#       storage: 4Gi

# ---

apiVersion: v1
kind: Service
metadata:
  name: statefullset-headless-service
  labels:
    purpose: statefullset-demo
    project: roboshop

spec:
  clusterIP: None
  selector:
    purpose: statefullset-demo
    project: roboshop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: statefullset-service
  labels:
    purpose: statefullset-demo
    project: roboshop
spec:
  selector:
    purpose: statefullset-demo
    project: roboshop
  ports:
  - protocol : TCP
    port: 80
    targetPort: 80

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefullset
  labels:  # this should match .spec.template.metadata.labels
    purpose: statefullset-demo
    project: roboshop
spec:
  replicas: 3
  serviceName: statefullset-headless-service   # this should be headless service
  selector:
    matchLabels:
      purpose: statefullset-demo
      project: roboshop
  template:
    metadata:
      labels:  # this should match .spec.selector.matchLabels
        purpose: statefullset-demo
        project: roboshop
    spec:
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
          - name: persistent-volume
            mountPath: /usr/share/nginx/html

      
  volumeClaimTemplates:
    - metadata:
        name: persistent-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: ebs-dynamic-sc
        resources:
          requests:
            storage: 4Gi
